# Configuration of Econoblocks. For help, visit https://docs.axelli.net/

# Message handling.
message:
  # Should the plugin send messages about money gained?
  enabled: true

  # How should the plugin display messages when a player is given money?
  # NOTE: Some options will only work with select versions. You can see which below.
  # OPTIONS: CHAT, ACTION_BAR (1.12+), HOLOGRAM (1.12+)
  message-type: CHAT

  # HOLOGRAMS
  # This will only work if you have holograms set as your type.
  holograms:
    # OPTIONS: STAY, FLOAT, BOUNCE
    animation: STAY
    # This option will effect animations.
    # How long should the hologram stay? This is in seconds.
    duration: 1

# The checks system provides methods to help make sure players can't duplicate rewards.
checks:
  # This option uses SQLite. SQL support will come later.
  storage:
    # Should blocks be stored in a database? This will keep all block data across restarts. Setting this option to false will still keep track of blocks,
    # but they will NOT be saved across restarts.
    enabled: true
    # How long will blocks be stored for until they expire? This will help clear up space in the database.
    # To disable this, just set it to 0. This is in days.
    expiry: 3

# Multiplier handling.
# If any conditions are true, they will be considered towards the output amount.
# Make sure to balance this properly if you use both. You can leave any category empty if you wish not to use it.
multipliers:
  tools:
    - IRON_PICKAXE 1.05
    - GOLD_PICKAXE 1.1
    - DIAMOND_PICKAXE 1.2
  worlds:
    - world1 1.8

# A list of worlds where money wont be given.
world-blacklist:
  - world2