# Configuration of Econoblocks. For help, visit https://docs.axelli.net/
checks:
  # Should money be given if the tool has silk touch on it?
  allow-silk-touch: false

# Multipliers.
# If any conditions are true, they will be considered towards the output amount.
# Make sure to balance this properly if you use both. You can leave any category empty if you wish not to use it.
multipliers:
  tools:
    - IRON_PICKAXE 1.05
    - GOLD_PICKAXE 1.1
    - DIAMOND_PICKAXE 1.2
  worlds:
    - world1 1.8

# A list of worlds where money wont be given.
world-blacklist:
  - world2